% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Z:\Korschunov\Praxisphase\Messungen\Equalizer\SNR\MSO7034Data.csv
%
% Auto-generated by MATLAB on 17-Jul-2024 11:09:01

% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["xaxis", "MATH"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Data = readtable("Z:\Korschunov\Praxisphase\Messungen\Equalizer\SNR\MSO7034Data.csv", opts);


% Clear temporary variables
clear opts


% Plotte FFT
figure; 
p = plot(Data.xaxis, Data.MATH);

xlabel('Frequenz [Hz]');
ylabel('Amplitude [dB]');
grid on;

xlim([min(Data.xaxis), max(Data.xaxis)]);
ylim([min(Data.MATH), max(Data.MATH)]);




% Maximalwert Amplitude 
maxAmplitude_db = max(Data.MATH)


% Filter the data to exclude the specified frequency ranges
excludedRanges = ((Data.xaxis >= 1800 & Data.xaxis <= 2200) | ...
                  (Data.xaxis >= 3800 & Data.xaxis <= 4200));
filteredData = Data(~excludedRanges, :);

% Calculate the mean of the remaining IN2 values
meanValue_dB = mean(filteredData.MATH)

% Berechnung des SNR
SNR_dB = maxAmplitude_db - meanValue_dB

