close all;
clear all;

% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Z:\Korschunov\Praxisphase\Messungen\Equalizer\SNR\RedPitayaData.csv
%
% Auto-generated by MATLAB on 17-Jul-2024 11:04:10

% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FrequencykHz", "IN2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Data = readtable("Z:\Korschunov\Praxisphase\Messungen\Equalizer\SNR\RedPitayaData.csv", opts);


% Clear temporary variables
clear opts


% Plotte FFT
figure; 
p = plot(Data.FrequencykHz, Data.IN2+30);

xlabel('Frequenz [kHz]');
ylabel('Amplitude [dB]');
grid on;

xlim([min(Data.FrequencykHz), max(Data.FrequencykHz)]);
ylim([min(Data.IN2+30), max(Data.IN2+30)]);



% Maximalwert Amplitude 
maxAmplitude_db = max(Data.IN2+30)


% Filter the data to exclude the specified frequency ranges
excludedRanges = ((Data.FrequencykHz >= 1.8 & Data.FrequencykHz <= 2.2) | ...
                  (Data.FrequencykHz >= 3.8 & Data.FrequencykHz <= 4.2));
filteredData = Data(~excludedRanges, :);

% Calculate the mean of the remaining IN2 values
meanValue_dB = mean(filteredData.IN2+30)

% Berechnung des SNR
SNR_dB = maxAmplitude_db - meanValue_dB


