% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Z:\Korschunov\Praxisphase\Messungen\Equalizer\Bodediagramm\Red Pitaya\xxxx.csv
%
% Auto-generated by MATLAB on 17-Jul-2024 07:50:12

% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FrequencyHz", "AmplitudedB", "Phasedeg"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Data1 = readtable("Z:\Korschunov\Praxisphase\Messungen\Equalizer\Bodediagramm\Red Pitaya\751212.csv", opts);
Data2 = readtable("Z:\Korschunov\Praxisphase\Messungen\Equalizer\Bodediagramm\Red Pitaya\951212.csv", opts);
Data3 = readtable("Z:\Korschunov\Praxisphase\Messungen\Equalizer\Bodediagramm\Red Pitaya\1251212.csv", opts);
Data4 = readtable("Z:\Korschunov\Praxisphase\Messungen\Equalizer\Bodediagramm\Red Pitaya\351212.csv", opts);
Data5 = readtable("Z:\Korschunov\Praxisphase\Messungen\Equalizer\Bodediagramm\Red Pitaya\551212.csv", opts);
% Clear temporary variables
clear opts

% Verify data1 import
%disp(Data1);

% Plotte Amplitudengang1
figure; 
subplot(2,1,1)
p = semilogx(Data1.FrequencyHz, Data1.AmplitudedB);

hold on

% Plotte Amplitudengang2
%figure; 
subplot(2,1,1)
p = semilogx(Data2.FrequencyHz, Data2.AmplitudedB);

% Plotte Amplitudengang3
%figure; 
subplot(2,1,1)
p = semilogx(Data3.FrequencyHz, Data3.AmplitudedB);

% Plotte Amplitudengang4
%figure; 
subplot(2,1,1)
p = semilogx(Data4.FrequencyHz, Data4.AmplitudedB);

% Plotte Amplitudengang5
%figure; 
subplot(2,1,1)
p = semilogx(Data5.FrequencyHz, Data5.AmplitudedB);

xlabel('Frequenz [Hz]');
ylabel('Amplitude [dB]');
grid on;

xlim([min(Data1.FrequencyHz), max(Data5.FrequencyHz)]);
ylim([min(Data1.AmplitudedB), max(Data5.AmplitudedB)]);


hold off


% Plotte Phasengang1
subplot(2,1,2)
p = semilogx(Data1.FrequencyHz, Data1.Phasedeg);

hold on

% Plotte Phasengang2
subplot(2,1,2)
p = semilogx(Data2.FrequencyHz, Data2.Phasedeg);


% Plotte Phasengang3
subplot(2,1,2)
p = semilogx(Data3.FrequencyHz, Data3.Phasedeg);


% Plotte Phasengang4
subplot(2,1,2)
p = semilogx(Data4.FrequencyHz, Data4.Phasedeg);


% Plotte Phasengang5
subplot(2,1,2)
p = semilogx(Data5.FrequencyHz, Data5.Phasedeg);
xlabel('Frequenz [Hz]');
ylabel('Phase [deg]');
grid on;

xlim([min(Data1.FrequencyHz), max(Data5.FrequencyHz)]);
ylim([min(Data1.Phasedeg), max(Data5.Phasedeg)]);

hold off
